name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@d02c89dce7e1ba9ef629ce0680989b3a1cc72edb
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c

    - name: Install dependencies
      run: pnpm i
      shell: bash
