name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Setup Node.js
      uses: actions/setup-node@b9b25d45f70a5d94d88496aa4896bf9ed8f49b67
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

    - name: Install dependencies
      run: pnpm i
      shell: bash
