name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

    - name: Setup Node.js
      uses: actions/setup-node@08f58d1471bff7f3a07d167b4ad7df25d5fcfcb6
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0

    - name: Install dependencies
      run: pnpm i
      shell: bash
