name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Setup Node.js
      uses: actions/setup-node@5e2628c959b9ade56971c0afcebbe5332d44b398
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0

    - name: Install dependencies
      run: pnpm i
      shell: bash
