name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

    - name: Setup Node.js
      uses: actions/setup-node@633bb92bc0aabcae06e8ea93b85aecddd374c402
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

    - name: Install dependencies
      run: pnpm i
      shell: bash
