name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

    - name: Setup Node.js
      uses: actions/setup-node@7e24a656e1c7a0d6f3eaef8d8e84ae379a5b035b
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0

    - name: Install dependencies
      run: pnpm i
      shell: bash
