name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

    - name: Setup Node.js
      uses: actions/setup-node@dda4788290998366da86b6a4f497909644397bb2
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

    - name: Install dependencies
      run: pnpm i
      shell: bash
