name: Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5
      with:
        node-version-file: '.nvmrc'

    - name: Install pnpm
      uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c

    - name: Install dependencies
      run: pnpm i
      shell: bash
