name: Common Setup

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f

    - name: Setup Node.js
      uses: actions/setup-node@08f58d1471bff7f3a07d167b4ad7df25d5fcfcb6
      with:
        node-version: 24

    - name: Install pnpm
      uses: pnpm/action-setup@d648c2dd069001a242c621c8306af467f150e99d
      with:
        version: 10.12.1

    - name: Install dependencies
      run: pnpm i
